---
title: "DVS Analysis"
author: "Amit Levinson"
date: "2/6/2022"
output:
  html_document:
    theme: united
    highlight: tango
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Below we'll be analyzing the DVS survey results.


```{r}
library(googlesheets4)
library(readr)
library(janitor)
library(tidyr)
library(dplyr)
library(ggplot2)
library(forcats)
library(stringr)
library(tidygraph)
library(ggraph)
```

```{r}
# dat_raw <- read_sheet("https://docs.google.com/spreadsheets/d/1lDkxioTmT5--JufJuYryiV5fKsdQQopvlSJO4Gh0ors/edit#gid=532705671", sheet = "data_2021_main", skip = 3)
# write_csv(dat_raw, "survey_results.csv")
```

```{r}
dat_raw <- read_csv("survey_results.csv") %>% 
  clean_names()  

theme_set(theme_minimal() +
            theme(
              text = element_text(family = "Raleway"),
              plot.title = element_text(family = "Merriweather", size = 16, face = "bold"),
              plot.title.position = "plot",
              panel.grid.minor.x = element_blank()
            )
          )
```


### Various roles


```{r}
dat_1to60 <- dat_raw %>% 
  select(1:60)
  
```

What roles do respondents have?

```{r}
dat_1to60 %>% 
  pivot_longer(cols = starts_with("dv_roles_"), names_prefix = "dv_roles_", names_to = "role", values_to = "response", values_drop_na = TRUE) %>% 
  count(response) %>% 
  mutate(response = str_wrap(response, 40),
        response= fct_reorder(response, n)) %>% 
  ggplot(aes(y= response, x = n))+
  geom_col() +
   theme(
     panel.grid.major.y = element_blank()
   )
```

Years of experience [q06]

```{r}
dat_1to60 %>% 
  count(years_dv_experience) %>% View()
factor(dat_1to60$years_dv_experience)
dat_1to60 %>% 
  mutate(
         years_dv_experience = factor(years_dv_experience, levels = c("Less than 1 year", "1" , "2", "3", "4", "5", "6–10", "11–15","16–20", "21–25", "26–30", "More than 30"), exclude = NA)) %>%
  count(years_dv_experience) %>% 
  ggplot(aes(y= years_dv_experience, x = n))+
  geom_col() +
   theme(
     panel.grid.major.y = element_blank()
   ) + 
  labs(title = "Years of DV experience")

```

What is respondents' salary? 

```{r}
dat_1to60 %>% 
  count(pay_annual, sort = T) %>% 
  mutate(
    pay_annual = factor(pay_annual)
  ) %>% 
  ggplot(aes(y= pay_annual, x = n))+
  geom_col() +
   theme(
     panel.grid.major.y = element_blank()
   ) +
  labs(
    title = "Respondents' salaries"
  )
```

### Tools people use

```{r}
tools_used <- dat_raw %>% 
  pivot_longer(cols = contains("tools_for_dv_"), names_prefix = "tools_for_dv_", values_to = "tool",values_drop_na = TRUE) %>% 
  pivot_longer(cols = starts_with("dv_roles_"), names_prefix = "dv_roles_", names_to = "role", values_to = "response", values_drop_na = TRUE) %>% 
  select(chron_id ,  response, tool)
```

Tools used distinctly by respondent:

```{r}
tools_used %>% 
  distinct(chron_id, tool) %>% 
  count(tool, sort = T)
```

Tools used per work category?

```{r fig.width = 10}
tools_used %>% 
  count(response, tool, sort = T) %>% 
  filter(n > 49) %>% 
  mutate(
    response = str_wrap(response, width = 40)
  ) %>% 
  ggplot(aes(x = tool, y = response, fill = n)) +
  geom_tile() +
  theme(
    axis.text.x = element_text(angle = 90)

  ) + 
  labs(title = "Viz tools and respondents work career") 

top_25_tools <- tools_used %>% 
  distinct(chron_id, tool) %>% 
  count(tool, sort = T) %>% 
  slice(1:25) %>% 
  pull(tool)
```

### Tools people use together

```{r}
# Extract 25 most frequently used tools
tools_used_respodnent <- tools_used %>% 
  filter(tool %in% top_25_tools) %>% 
  distinct(chron_id, tool)

# Top 15 tools for adding node name
top_15_tools <- tools_used_respodnent %>% 
  distinct(chron_id, tool) %>% 
  filter(tool %in% top_25_tools) %>% 
  count(tool, sort = T) %>% 
  slice(1:15) %>% 
  pull(tool)

# Tools used by respondent combination
tools_agg <- tools_used_respodnent %>% 
  full_join(tools_used_respodnent, by = "chron_id") %>% 
  filter(tool.x < tool.y) %>% 
  count(tool.x, tool.y)
```

```{r}
tools_graph <- as_tbl_graph(tools_agg) %>% 
  activate(nodes) %>% 
  mutate(
    node_label = ifelse(name %in% top_15_tools, name, NA)
  )
```

```{r}
ggraph(tools_graph, layout = "stress") +
  geom_node_point(color = "gray55", alpha = 0.8) +
  geom_edge_link(aes(alpha = n), show.legend = FALSE)+
  geom_node_text(aes(label = node_label)) +
  theme_graph() + 
  labs(title = "Combination of tools respondents use")
```


